Print error after EOL for cosmetic purposes
Before this, it would look weird because of the line numbers:

```
Failed to fetch PPQ.ai models: 33 |   const lowered = modelId.toLowerCase();
34 |
35 |   // e.g. AutoClaw and Auto
36 |   return lowered.startsWith("auto") ||
37 |
38 |   startsWith("free");
                 ^
ReferenceError: startsWith is not defined
``