chore: rename&bump&NPM-publish pkg&deps
Rename done in macOS via these commands:

```
sed -i '' -e 's/\@mariozechner\/pi-coding-agent/awto-pi-lot/g' **/*.json
sed -i '' -e 's/\@mariozechner\/pi-coding-agent/awto-pi-lot/g' **/*.ts
sed -i '' -e 's/\@mariozechner\/pi-coding-agent/awto-pi-lot/g' .*/**/*.ts
```

We couldn't use the name 'auto-pi-lot' because
npm's server replied with this error when publishing:

```
npm notice Publishing to https://registry.npmjs.org/ with tag latest and public access
npm error code E403
npm error 403 403 Forbidden - PUT https://registry.npmjs.org/auto-pi-lot - Package name too similar to existing packages autopilot,auto-pilot; try renaming your package to '@knocte/auto-pi-lot' and publishing with 'npm publish --access=public' instead
npm error 403 In most cases, you or one of your dependencies are requesting
npm error 403 a package version that is forbidden by your security policy, or
npm error 403 on a server you do not have access to.
npm error A complete log of this run can be found in: /home/runner/.npm/_logs/2026-03-17T18_33_51_069Z-debug-0.log
Error: Process completed with exit code 1.
```

We had to rename&publish the subpackages too because
otherwise we would get this kind of errors when using
awto-pi-lot via npx:

```
Need to install the following packages:
  awto-pi-lot@1.59.0
Ok to proceed? (y) y
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @mariozechner/pi-agent-core@^1.59.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2026-03-17T19_31_53_583Z-debug-0.log
```

And we couldn't rename them to 'awto-pi-lot/sub-pkg-name' style
because 'foo/bar' is not allowed I guess (but @foo is if it's
your username), judging by this error message:

```
Run npm ci
npm error code EINVALIDPACKAGENAME
npm error Invalid package name "awto-pi-lot/pi-agent-core" of package "awto-pi-lot/pi-agent-core@file:/home/runner/work/awto-pi-lot/awto-pi-lot/packages/agent": name can only contain URL-friendly characters.
npm error A complete log of this run can be found in: /home/runner/.npm/_logs/2026-03-17T20_10_34_295Z-debug-0.log
Error: Process completed with exit code 1.
```